# Preface {-}

This book is designed as the lecture notes and textbook for 
[BIOF1001: Introduction to Biomedical Data Science](),
an undergraduate course (Year 1) at the University of Hong Kong.

This book is not aimed to be a comprehensive textbook, but rather more 
Rmarkdown notebooks as supplementary to lecture notes so that students can 
reproduce the teaching contents more easily.

## Introduction for readers {-}

### What you will learn from this course/book {-}
In part I, you will find a general introduction to data science (by Dr YH Huang):

2) Basic programming and visualisation skills: R scripts for the quantitative 
   methods and data visualisation.
1) Quantitative methods: t-test, correlation analysis, clustering, linear 
   regression, linear classification.
3) Gain familiarity with common databases in the biomedical domain. 
4) Introduce ethical, legal, social and technological issues related to 
   biomedical data sciences.
5) Introduce good practice in managing a data science project and communicate 
   results to key stakeholders.

In part II, you will experience data types in four different biomedical topics,
which will be illustrated with both introduction and cases that are suitable for
problem-based learning format:

1) Medical imaging and digital health, by Dr Joshua Ho and Dr Rachel Kwan
2) Infectious disease informatics, by Dr Tommy Lam and Dr Kathy Leung
3) Cancer genomics and epidemiology, by Dr David Shih and Dr Jason Wong
4) Population genetics and diseases, by Dr Clara Tang and Dr Asif Javed

### What we recommend you do while reading this book {-}
To enhance the knowledge and skills learned from this book, we recommend that
readers

1) Read the materials/slides provided in each module
2) Practice quantitative skills by solving problems using R

## Other reference books {-}

Besides this online book as a collection of R materials for the teaching 
contents, we also recommend the following online books as reference:

1. [Introduction to Data Science: Data Wrangling and Visualization with R](http://rafalab.dfci.harvard.edu/dsbook-part-1/) by Rafeal A. Irizarry
2. [Advanced Data Science: Statistics and Prediction Algorithms Through Case Studies](http://rafalab.dfci.harvard.edu/dsbook-part-2/) by Rafeal A. Irizarry


## Acknowledgements {-}

We thank all teachers contributing to this course across all years, including 
Dr Lequan Yu (2022-23) and Dr Carlos Wong (2022-23) and student helpers serving 
as demonstrators, including Mr Mingze Gao and Ms Fangxin Cai.

<!-- ## Last notes {-} -->



<!-- # About the authors {-} -->

<!-- The authors are the teaching team for the BIOF1001 course (ordered by teaching  -->
<!-- time): -->

<!-- * Dr Yuanhua Huang (course coordinator) -->
<!-- * Dr David Shih -->
<!-- * Dr Joshua Ho -->
<!-- * Dr Lequan Yu -->
<!-- * Dr Tommy Lam -->
<!-- * Dr Kathy Leung -->
<!-- * Dr Clara Tang -->
<!-- * Dr Asif Javed -->
<!-- * Dr Jason Wong -->
<!-- * Dr Carlos Wong -->

